### ISSUE TITLE
Functionality and Design

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/sidekiq-statistic#1]
## Main info
[[wiki page]](https://github.com/davydovanton/sidekiq-history/wiki/GSoC-proposal-for-Ruby-organization-(Sidekiq))

**Comment by davydovanton** [comment]
@mperham what do yo think about my ideas? I think that if we adopt these ideas, I can do it yourself a couple of weeks :smiley:

**Comment by mperham** [comment]
A couple of thoughts:

1. Saving error and backtrace information is already done by Sidekiq's retry functionality and sidekiq-failures.  Why duplicate it?
2. You use the word "worker" a lot where I think you might mean "job".  Worker is a Class.  Job is an instance of that class that is executed via `perform`.  Jobs have a JID.  Is your History plugin going to track history per Job or per Worker?  If per Worker, is it going to track it per Day, per Hour or maybe per Deploy?

per Worker, per Day:

Worker | Date | Success | Failure | Total Time (sec) | Average (sec) | StdDev (sec) |
--------- | -------- | ------------ | -------- | ---------------| ---------------- | ------- |
MyWorker | 2015-02-27 | 100 | 10 | 220.0 | 2 | 0.2 |
MyWorker | 2015-02-28 | 100 | 10 | 330.0 | 3 | 0.5 |

If you track per Job, you will quickly overwhelm Redis with data.  Many Sidekiq users process millions of jobs per day.

**Comment by davydovanton** [comment]
I like your idea about tracking per Worker. 
But in some cases I need informations about each job. For example, in my company in one project we use sidekiq for calculations loans and I want to know the status of each Job. That is why I come up with `tracking: false` option (maybe it would be better to call it `job_tracking: false`).

**Comment by davydovanton** [comment]
@mperham i think that we need add `Recently run` column where display last run time for passed worker.
Also, I have another idea. Maybe it would be good to add a web log?  Something like as in travis or heroku, what do you think about this? *(now this only idea, because sometimes I'm too lazy to look at the server log or I don't have access to server)*

**Comment by davydovanton** [comment]
I told about something like this but for log
![screenshot 2015-03-04 22 41 30](https://cloud.githubusercontent.com/assets/1147484/6491638/bc227908-c2bf-11e4-809e-09da4f7522e4.jpg)

**Comment by davydovanton** [comment]
I thought for a moment and mark up two pages. This is my vision of what I wanted to see in this plugin.
On the first page you can see the table with all the worker is as you suggested.
![screenshot 2015-03-05 00 07 26](https://cloud.githubusercontent.com/assets/1147484/6493597/c981286c-c2cc-11e4-93c0-aeed8ab20e3d.jpg)
And if you click on the link(worker name), it opens a second page, which would display a piece of log (the last N records) for this worker`s.
![screenshot 2015-03-05 00 07 19](https://cloud.githubusercontent.com/assets/1147484/6493614/df527a92-c2cc-11e4-8b80-31c79c4d5aca.jpg)

**Comment by davydovanton** [comment]
Also, I have suggested that it would be great to show graphic with all jobs for each worker, for example something like this.
![screenshot 2015-03-07 17 36 51](https://cloud.githubusercontent.com/assets/1147484/6541712/321c8d96-c4f1-11e4-9358-0e37977dc931.jpg)

@mperham what do you think about this?

**Comment by mperham** [comment]
Yeah, that's called a Stacked Area Graph. https://en.wikipedia.org/wiki/Area_chart

That graph should be pretty easy to build.  I think it would be a great first bit of functionality for you to implement.

**Comment by davydovanton** [comment]
@mperham okay, I will try to implement this as soon as possible. And what do you think about [my pages design conception](https://github.com/davydovanton/sidekiq-history/issues/1#issuecomment-77249991)?

**Comment by mperham** [comment]
I suspect the log viewer is less useful than you might think.  Most people have Sidekiq running on multiple machines with logs piped to a service like Papertrail, or using Heroku with the logs not easily accessible from the Web UI.  Your log viewer would work in the simplest case of someone running Sidekiq and the Web UI on a single machine but I don't see how it would scale.

Open Source is all about solving your own problem.  If you have this problem and you are ok with limiting the log viewer to localhost then by all means do it.  But don't build this log viewer because you think other people might want it.

**Comment by davydovanton** [comment]
@mperham thanks for comments! : thumbsup: And as I said I need this functionality (log in web ui). That is why i want to create this :smiley:

**Comment by davydovanton** [comment]
@mperham I created simple charts for failed and passed jobs. This is not the finished version, but now you can imagine how it will look.
![screenshot 2015-03-08 04 18 08](https://cloud.githubusercontent.com/assets/1147484/6544005/8b0db282-c54a-11e4-9433-1378cbdfa38a.jpg)

**Comment by davydovanton** [comment]
@mperham hello, I'm sorry to interrupt but i have a question. What do you think what is the best way to add custom assets in to my plugin? I have not found a way to do this without using rails and it's awful for me :cold_sweat:

**Comment by mperham** [comment]
I'm not sure how to do this.

**Comment by davydovanton** [comment]
@mperham Hello again :smiley: I'm sorry to interrupt but I completed charts. You can see them in this page:
https://sidekiq-history-gem.herokuapp.com/sidekiq/history
*(in phone you can see dots instead charts. it's associated with css style for mobile. I will fix this later. Also charts not update in realtime. I want fix this too)*
And now i think start creating table for workers. What do you think?

*P.S. may be i will be send reports and some questions to you mail?*

**Comment by davydovanton** [comment]
@mperham I think I found a solution acceptable to me to add custom css file. For this I created PR (now you can see it on my repository davydovanton/sidekiq#2) where I created `custom_css` helper which provides the ability to add new css files to `layout` template. What do you think it's normal solution for my problem?

**Comment by davydovanton** [comment]
sorry, but my solution doesn't work correctly

**Comment by mperham** [comment]
I think Sinatra has an array of paths for serving static files.  Maybe you need to add your gem's public asset directory to that array.  Take a look at the impl for this gem, perhaps it will help: https://github.com/wbzyl/sinatra-static-assets/  Also, http://stackoverflow.com/questions/5055489/sinatra-static-assets-are-not-found-when-using-rackup

Hope this helps.  The screenshots you have so far look promising!

GSoC student registration starts on 3/16.  You'll need to register then.

**Comment by davydovanton** [comment]
@mperham hello! I completed table with worker informations :tada: You can see it in this screenshot:
![screenshot 2015-03-15 00 33 53](https://cloud.githubusercontent.com/assets/1147484/6653660/b3e502bc-caab-11e4-8be6-d839f5a7c79c.jpg)
But if you want see this table in real live you always can open my dev heroku application: 
https://sidekiq-history-gem.herokuapp.com/sidekiq/history

And thank you for the help with assets. I will check it in the near future :smiley:

And now I want start develop worker page with log parsing.

*P.S.: I'd really appreciate your comments on this. Thanks.*
*P.S.S.: Thanks for the reminder about registration :grimacing:*

**Comment by davydovanton** [comment]
@mperham  hello! I wrote proposal and would very much like what you would it have looked before I send it.
https://github.com/davydovanton/sidekiq-history/wiki/GSoC-proposal-for-Ruby-organization-(Sidekiq)
*P.S.: All grammatical errors I will fix tomorrow.*

**Comment by mperham** [comment]
I think it looks great.  Thanks for filling out the proposal.

**Comment by davydovanton** [comment]
@mperham you will not mind if I also thank you for your help in my proposal? :smiley:

**Comment by mperham** [comment]
Sure, go ahead.  :-)
