### ISSUE TITLE
undefined method `reverse!' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by romanvbabenko** [davydovanton/sidekiq-statistic#103]
I try to run the plugin as in standalone mode as it described in the manual, but got this error

```ruby
require 'sidekiq/web'
require 'sidekiq-statistic'

use Rack::Session::Cookie, secret: 'some-unique-secret-string-here'
Sidekiq::Web.instance_eval { @middleware.reverse! } # Last added, First Run
#
run Sidekiq::Web
```

```ruby
config.ru:5:in `block (2 levels) in <main>': undefined method `reverse!' for nil:NilClass (NoMethodError)
```

Ruby 2.3.1

**Comment by davydovanton** [comment]
@romanvbabenko, thanks for report 👍
Could you show full stack trace for this problem? (in gist)

**Comment by Daniel-ltw** [comment]
My workaround is: 

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Server::Logging
    chain.add Sidekiq::Middleware::Server::RetryJobs
    chain.add Sidekiq::Statistic::Middleware
  end
end
```

Have to do the middleware layer manually. 
Could skip the instance_eval line, in their example.

**Comment by vitaliy-cro** [comment]
@davydovanton the same issue with the same config
sidekiq (4.2.10)
 
`Traceback (most recent call last):
        33: from bin/rails:3:in `<main>'
        32: from bin/rails:3:in `load'
        31: from /Users/vitaliy/Projects/ruby/cheapsea/bin/spring:13:in `<top (required)>'
        30: from /Users/vitaliy/Projects/ruby/cheapsea/bin/spring:13:in `require'
        29: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        28: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        27: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        26: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        25: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        24: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        23: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        22: from /Users/vitaliy/Projects/ruby/cheapsea/bin/rails:9:in `<top (required)>'
        21: from /Users/vitaliy/Projects/ruby/cheapsea/bin/rails:9:in `require'
        20: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
        19: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        18: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:85:in `server'
        17: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:85:in `tap'
        16: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        15: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/server.rb:102:in `start'
        14: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/server.rb:148:in `log_to_stdout'
        13: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
        12: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/server.rb:84:in `app'
        11: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
        10: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
         9: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
         8: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
         7: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
         6: from /Users/vitaliy/Projects/ruby/cheapsea/config.ru:in `<main>'
         5: from /Users/vitaliy/Projects/ruby/cheapsea/config.ru:in `new'
         4: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
         3: from /Users/vitaliy/.rvm/gems/ruby-2.5.1/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
         2: from /Users/vitaliy/Projects/ruby/cheapsea/config.ru:11:in `block in <main>'
         1: from /Users/vitaliy/Projects/ruby/cheapsea/config.ru:11:in `instance_eval'
/Users/vitaliy/Projects/ruby/cheapsea/config.ru:11:in `block (2 levels) in <main>': undefined method `reverse!' for nil:NilClass (NoMethodError)`

**Comment by wenderjean** [comment]
@davydovanton There something else we should do here? I believe we can close this issue.

**Comment by wenderjean** [comment]
It seems the update in README regarding standalone configuration helped to solve the problem. I'm closing this issue considering we haven't been having activities on it.
