### ISSUE TITLE
Understanding stats

### ISSUE THREAD

**Issue by bgvo** [davydovanton/sidekiq-statistic#110]
![Image](https://cloud.githubusercontent.com/assets/1147484/8071171/1706924a-0f10-11e5-9ddc-8aeeb7f5c794.png)

I'm not sure what some of the columns mean. First five are clear, but from there on numbers change over time up and down and not sure what the relations are among them. Could any explain what are they referring to? (Time(sec), Average(sec), etc.)

**Comment by davydovanton** [comment]
Hey!
Yes, of course:

`Time(sec)`: total time which you jobs work in seconds (`jobs count` * `average`)
`Average(sec)`: average duration for all jobs in seconds (`total` / `jobs count`)
`Min time(sec)`: minimal time for running one job in seconds ((`array of each jobs time`).min)
`Min time(sec)`: maximal time  for running one job in seconds ((`array of each jobs time`).max)
