### ISSUE TITLE
Charts are no longer visible when you have a lot of workers

### ISSUE THREAD

**Issue by wenderjean** [davydovanton/sidekiq-statistic#140]
We add `statistic` in a big project for our company and we realize that when we are dealing with a bunch of workers the graphics are compacted by the list of worker names.

**Comment by GQuirino** [comment]
I generate 50 random data to check this issue.

![image](https://user-images.githubusercontent.com/15057257/65331671-9b148700-db93-11e9-8d31-3dc077097480.png)

this chart is being replaced in this pr #139

**Comment by wenderjean** [comment]
Yeah, that's similar we're getting here.
