### ISSUE TITLE
Improve hide feature on real-time tab

### ISSUE THREAD

**Issue by wenderjean** [davydovanton/sidekiq-statistic#154]
The table below looks kinda weird with a checkbox to hide workers, I suggest some improvements like:

1. Switch columns position (Worker | Visible)
2. Turn the checkbox into a button (show/hide)

![image](https://user-images.githubusercontent.com/941776/86009739-f449fa80-b9f0-11ea-9df3-23bedda42278.png)

**Comment by kostadriano** [comment]
I would like to work on this issue :)

**Comment by wenderjean** [comment]
Great @kostadriano, feel free to work on it :)
