### ISSUE TITLE
Color of visited anchors is hard to read on dark mode

### ISSUE THREAD

**Issue by johnmanjiro13** [davydovanton/sidekiq-statistic#160]
Sidekiq supports dark mode, but color of visited anchors in the workers table remains as in white mode.
Its color code is `#4b001a`.
I think this color is hard to read on dark mode. 
So, what do you think about change it to `#ccc` like sidekiq on dark mode?

**Comment by wenderjean** [comment]
I pretty much agree on a handle to this issue @johnmanjiro13, would you like to address that?

**Comment by V-Gutierrez** [comment]
Could you assign it to me ? I want to work on it
