### ISSUE TITLE
Empty workers

### ISSUE THREAD

**Issue by juliofalbo** [davydovanton/sidekiq-statistic#177]
Hi.

I just added the gem in my Rails app but the Statistic is empty and the endpoint is also returning `{"workers":[]}`, but as you can see in the image below, I have workers running and jobs being executed.

![image](https://user-images.githubusercontent.com/6312265/139676628-26fb316f-a950-4405-9ec7-6733ea924e75.png)
![image](https://user-images.githubusercontent.com/6312265/139676672-4937b49e-3e4e-40b5-93e8-c586e7f50d97.png)
 
I added the config below to my initializer.
```
Sidekiq::Statistic.configure do |config|
  config.max_timelist_length = 250_000
end
```

**Comment by juliofalbo** [comment]
My bad, I forgot to restart the sidekiq, now it is fine.

**Comment by wenderjean** [comment]
Thanks for the feedback, I'm closing it @juliofalbo.
