### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/sidekiq-statistic#23]
- [x] ~~Add option with log path for not default logfile [done]~~
- [x] ~~Add custom assets [done]~~
- [x] ~~Catch the error log of absence [done]~~
- [x] ~~Improve log web UI page [done]~~
- [x] ~~Add find in log [done]~~
- [x] ~~Add `max time` row to index table [done]~~
- [x] ~~Add `min time` row to index table [done]~~
- [x] ~~Specific color for each worker name [done]~~
- [x] ~~Add worker table for each day [done]~~
- [x] ~~Add live reload for index page [done]~~
- [x] ~~Fix displaying date on index page [done]~~
- [x] ~~Fix displaying last run time [done]~~
- [x] ~~Add row with status for last worker job [done]~~
- [x] ~~Show information for any time interval [done]~~
- [x] ~~Fix not thread safe middleware [done]~~
- [x] ~~Support AJ [done]~~
- [x] ~~Read first 1000 lines from logfile [done]~~
- [x] ~~Add external JSON API [done]~~
- [x] ~~Localizations  [done]~~
- [x] ~~Realtime chart for each worker [done]~~
- [x] ~~Add filters (by worker) for realtime chart [done]~~
- [x] ~~Save job runtime in redis list https://github.com/davydovanton/sidekiq-statistic/pull/33#discussion_r34944402 [done]~~
- [ ] ~~Update documentation [done]~~
- [ ] Integration with other services (like newrelic) (**undefined feature**)
- [ ] More system informations (**undefined feature**, ask from @mperham)
- [ ] Add to table next runtime (**undefined feature**)
- [ ] Sidekiq process from nix system tools (**undefined feature**)

**Comment by davydovanton** [comment]
Also, we use this gem in production.

index page:
![sidekiq-history_index](https://cloud.githubusercontent.com/assets/1147484/8071172/1708e3b0-0f10-11e5-84cf-86a910f5ecc2.png)

worker page with table (per day):
![sidekiq-history_worker](https://cloud.githubusercontent.com/assets/1147484/8071171/1706924a-0f10-11e5-9ddc-8aeeb7f5c794.png)

worker page with log:
![screenshot 2015-06-10 01 27 50](https://cloud.githubusercontent.com/assets/1147484/8071166/0edd7688-0f10-11e5-9841-0572ab5704e3.jpg)

**Comment by mperham** [comment]
That looks fantastic!  I will take a look at the code this weekend and open issues for anything that needs to be improved or redesigned.

**Comment by mperham** [comment]
A stacked graph might be better in that first picture but I'm not great with UI so I'll defer to others.

**Comment by davydovanton** [comment]
@mperham thanks for feedback! :)
I have some ideas with refactoring my code, yes. I will make this after realtime chart.

This screenshots from my production site(we have old version of gem). Now it look like this:
![screenshot 2015-06-10 23 24 46](https://cloud.githubusercontent.com/assets/1147484/8093170/02313e66-0fc8-11e5-8d59-6ca417df8135.jpg)

**Comment by nessur** [comment]
any plans on adding support for ActiveJob ? :)

<img width="1221" alt="screen shot 2015-07-15 at 12 06 02 pm" src="https://cloud.githubusercontent.com/assets/99211/8703177/f35f8446-2ae9-11e5-8fb8-fee07c4ee9b6.png">

**Comment by mperham** [comment]
You can see what Sidekiq does to support AJ here:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L279

**Comment by davydovanton** [comment]
@nessur thanks for feedback, I fixed this in #29 

@mperham thanks for comment, I want use `wrapped` option from message hash

**Comment by digitalextremist** [comment]
Nice work @davydovanton :+1:

**Comment by davydovanton** [comment]
thank you @digitalextremist :blush:

**Comment by mperham** [comment]
Just so you know, Aug 17 is the suggested last date for coding and Aug 21 is the hard deadline when coding must stop.  You've got a few more steps to go in your list so just a reminder.

**Comment by davydovanton** [comment]
Yep, I remember, thanks @mperham!
Now I completed backend for realtime job information (https://github.com/davydovanton/sidekiq-statistic/pull/41).

I would like to clarify all tasks marked "undefined feature" (last 4) I plan to do after the deadline. Do you mind?

**Comment by mperham** [comment]
Yep, that release plan looks good.

**Comment by davydovanton** [comment]
[v1.0](https://github.com/davydovanton/sidekiq-statistic/releases/tag/v1.0) is out! :tada:

**Comment by rusterholz** [comment]
Congrats @davydovanton!
