### ISSUE TITLE
June review feedback

### ISSUE THREAD

**Issue by mperham** [davydovanton/sidekiq-statistic#24]
Hi Anton, this looks amazing so far.  You've got 90% of the functionality done already; I'm very impressed!  Here's a couple of issues I noted:

1. The project needs to be renamed to `sidekiq_history` or maybe something more distinctive.  Right now I have to use `gem 'sidekiq_history', require: 'sidekiq-history'` in the Gemfile, which is really awkward.  Maybe "worker-history", "job-history" or "sidekiq-chronicle"?  Naming is hard.
2. Making the user configure the logfile location should be a last resort, you can make the code a little smarter so it just works more often.  A hack lets you look into the logger to find the filename it is actually using: `Sidekiq.logger.instance_variable_get(:@logdev).filename`
3. Unfortunately your [history storage is not thread-safe](https://github.com/davydovanton/sidekiq-history/blob/master/lib/sidekiq/history/middleware.rb#L42) and will lose data under heavy load.  You are pulling data out of Redis, mutating it and then pushing it back to Redis.  If multiple threads are doing this, they can lose changes.  You'll need to redesign your history storage to use `multi` or atomic operations, like `incr`, `hincrby`, etc.  In general, avoid using JSON; store the data in native Redis datatypes if possible.

The last one is the major issue and solving it will teach you a lot more about Redis and threading.  You might start by writing a test which hammers the middleware with 20-30 concurrent threads and verifying the history statistics are wrong.  Once you've shown that, you can redesign the storage and see the test pass, even under heavy load.  I wrote [a similar test for Dalli](https://github.com/mperham/dalli/blob/master/test/test_dalli.rb#L568) years ago to prove the Dalli::Client threadsafe in MRI and JRuby.

**Comment by aprescott** [comment]
For (1) would it help to have `lib/sidekiq_history` which does nothing but `require "sidekiq/history"`?  That's a fairly standard way of tackling gem extension naming so that you don't need to do that Gemfile stunt. I like the name `sidekiq-history` personally.

**Comment by mperham** [comment]
There's already a gem by that name. https://rubygems.org/gems/sidekiq-history

**Comment by aprescott** [comment]
Sorry I meant `lib/sidekiq_history.rb` with the extension.

**Comment by aprescott** [comment]
Ohhh. I see.

**Comment by davydovanton** [comment]
Mike, thanks for feedback :blush: 
About first point: I think I'll rename gem to `sidekiq-statistic` or something else.  I don't like `history` name because I grab statistic information substantially. What do you think?

**Comment by davydovanton** [comment]
2. I don't know about this. It's great tips, thanks :star2:
3. Yes, you're absolutely right. Thanks for the tip

**Comment by davydovanton** [comment]
Also I want to remove this initializer from all my classes:
``` ruby
def initialize(days_previous, start_date = nil)
  @start_date = start_date || 
  @end_date = @start_date - days_previous
end
```

**Comment by davydovanton** [comment]
@mperham what do you think about `chronikiq`? :smile:

**Comment by mperham** [comment]
How's the project going?  Any ETA for this issue?  That's a clever name but I would be worried if people would remember how to spell it.  Ultimately it is your project and you can name it whatever you want.

**Comment by davydovanton** [comment]
@mperham I am working on thread-safe middleware now #26. I hope that I will complete this issue by the weekend :grimacing:

**Comment by sponomarev** [comment]
@davydovanton great work, thanx!
