### ISSUE TITLE
Filtering log by JID

### ISSUE THREAD

**Issue by marshall-lee** [davydovanton/sidekiq-statistic#40]
Hello!

I haven't looked at this project carefully but one of the screenshots looks very interesting to me. I mean a worker log.

The problem that I often face in my work is to look at what happened in the context of one job. Sidekiq logs are not human-friendly since many threads all write to one log file. Filtering logs by a worker class is not enough — I also need a convenient way to filter a log by JID (for now, I just fgrep by particular JID in my sidekiq.log).

I also see a 'Search text in log file` input box in this screenshot. So I think it would be useful to make JID in log *clickable* and on click simply insert JID in the text field and perform the search.

What do you think?

**Comment by marshall-lee** [comment]
As I see in your demo heroku app — filtering by JID works well when I just copy&paste it but I just need it to be automated.

**Comment by marshall-lee** [comment]
![screenshot from 2015-08-07 19 45 06](https://cloud.githubusercontent.com/assets/3194530/9140851/d8edee26-3d3c-11e5-9020-6b76ed97c7aa.png)

**Comment by davydovanton** [comment]
closed by #55
