### ISSUE TITLE
Redis key nesting inverted

### ISSUE THREAD

**Issue by felixbuenemann** [davydovanton/sidekiq-statistic#47]
The nesting of the redis keys is inverted compared to redis, eg. sidekiq uses `my_app:sidekiq:stat:processed:2015-05-31`, but sidekiq-statistic uses `my_app:sidekiq:2015-08-19:Foo::BarWorker:timeslist`.

The expected nesting would be: `my_app:sidekiq:timeslist:Foo::BarWorker:2015-08-19`.

**Comment by davydovanton** [comment]
It seems to me that this is not so important. Furthermore I think that remodel hash is bad idea. Thanks
