### ISSUE TITLE
charts.json not found when mounting sidekiq web into scope

### ISSUE THREAD

**Issue by tisba** [davydovanton/sidekiq-statistic#56]
In our setup we mount sidekiq web into a scope (`/backoffice` in our case).

While `/backoffice/sidekiq/statistic` loads properly, it is still tried to load `/sidekiq/statistic` which obviously fails.

As far as I can tell, this path is hardcoded in `statistics.js` (https://github.com/davydovanton/sidekiq-statistic/blob/2216c8fb6baa6e9d15d4689e24dbff5d7d1833ab/lib/sidekiq/statistic/views/statistic.js#L70).

**Comment by davydovanton** [comment]
Thanks for catch :+1: 
I fixed this in c8283e5

**Comment by tisba** [comment]
Great, thanks!

**Comment by tisba** [comment]
I'm not sure if related, but I've got another 404 for `charts.json` using the gem via git containing the above mentioned fix (at c8283e5).

At `/backoffice/sidekiq/statistic/Server::Worker` I get a 404 on `/backoffice/sidekiq/statistic/Server::Worker/charts.json`.

**Comment by davydovanton** [comment]
@tisba hello,
yes, I know about this bug :disappointed: 
I'll fix this in future, thanks!
