### ISSUE TITLE
Heroku demo is down

### ISSUE THREAD

**Issue by rosswilson** [davydovanton/sidekiq-statistic#57]
The Heroku demo application seems to be broken:

https://sidekiq-history-gem.herokuapp.com/sidekiq/statistic

And the root URL is generating a HTTP 500.

https://sidekiq-history-gem.herokuapp.com

**Comment by davydovanton** [comment]
yes, I know :sweat: 
Sorry, it's because I use free dyno. Try open the app tomorrow.
![screenshot 2015-08-21 12 16 43](https://cloud.githubusercontent.com/assets/1147484/9405215/a4889db2-47fe-11e5-85e4-1a07c652c5b7.jpg)

**Comment by davydovanton** [comment]
oh, no, sorry, you're right  :sweat:

**Comment by davydovanton** [comment]
Updated heroku app, now you can open this
