### ISSUE TITLE
Truncated graph labels

### ISSUE THREAD

**Issue by zhulik** [davydovanton/sidekiq-statistic#63]
If you have many workers, you can see something like this
![screen](https://cloud.githubusercontent.com/assets/287062/9494548/23c67432-4c0f-11e5-9468-af1aff8a4d18.png)

As you can see, labes is trancated frome above

**Comment by davydovanton** [comment]
Thanks!
But I think the problem in charts.js library :disappointed:

**Comment by zhulik** [comment]
I agree, but in chart.js you can control content of labels and show only top 10 workers, for example. Also, try to update chart.js, maybe they already fix it;)

**Comment by davydovanton** [comment]
@zhulik hello, I found the problem :tada:
it's connected with `canvas`. So I can change chart.js library to c3.js or I can create custom tooltip.
Today I tried to custom tooltip and I found interesting bug (https://github.com/nnnick/Chart.js/issues/1422) :sweat:

**Comment by davydovanton** [comment]
Fixed in #64

**Comment by zhulik** [comment]
Great! Thanks!
