### ISSUE TITLE
Moving workers between queues

### ISSUE THREAD

**Issue by zhulik** [davydovanton/sidekiq-statistic#68]
I know, that worker management is not related with it's statistics, but sometimes sidekiq users need to do move scheduled and queued workers into other queues. Is to possible to implement this functionality is this gem?

**Comment by davydovanton** [comment]
So, interesting idea, but sidekiq-statistic only collect you job and (or) worker informations. I think you can send PR to sidekiq repository or write plugin special for this feature.
/cc @mperham

**Comment by mperham** [comment]
This is what the [Sidekiq API](https://github.com/mperham/sidekiq/wiki/API) is for.
