### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContext' of null

### ISSUE THREAD

**Issue by LaurensN** [davydovanton/sidekiq-statistic#70]
When trying to access the show of a worker:

http://localhost:3000/sidekiq/statistic/[Worker]

I'm receiving the following js error:

Uncaught TypeError: Cannot read property 'getContext' of null

The offending js function:

statistic.js - 138 
function createChart(type, data, datasets)

**Comment by davydovanton** [comment]
closed by #79
