### ISSUE TITLE
Issue with custom Date default format

### ISSUE THREAD

**Issue by stan** [davydovanton/sidekiq-statistic#74]
Sidekiq v3.5.0 - Sidekiq/Statistic v1.1

I'm using a custom Date::DATE_FORMATS[:default] in my application, and this breaks the expectation that `to_s` for a Date will always return something formatted as "%Y-%m-%d".

The following would fix this (and clarify my point) :

Replacing `(@end_date..@start_date).map(&:to_s)` by `(@end_date..@start_date).collect{|date| date.strftime "%Y-%m-%d"}` in https://github.com/davydovanton/sidekiq-statistic/blob/master/lib/sidekiq/statistic/base.rb#L44

Replacing `worker_key = "#{time.to_date}:#{status.delete :class}"` by `worker_key = "#{time.strftime "%Y-%m-%d"}:#{status.delete :class}"` in https://github.com/davydovanton/sidekiq-statistic/blob/master/lib/sidekiq/statistic/middleware.rb#L32 

Note that I raised a similar issue with Sidekiq mperham/sidekiq#2559

I'm not sure if this should be considered an issue with your code or not, I'll leave it to you to decide

**Comment by davydovanton** [comment]
@stan hello.
Thanks for bug report. And I'll be happy if you send PR with this changes :blush:
