### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/sidekiq-statistic#82]

**Comment by divoxx** [comment]
@davydovanton hey, I'm curious to know what memory leak is this. If there is a serious memory leak or no way around it I'll hold off using this in production until it gets fixed.

**Comment by shaicoleman** [comment]
I believe this is a duplicate of https://github.com/davydovanton/sidekiq-statistic/issues/73

**Comment by davydovanton** [comment]
@shaicoleman yes, I think you're right. Thanks!
