### ISSUE TITLE
ArgumentError - argument out of range

### ISSUE THREAD

**Issue by jhollinger** [davydovanton/sidekiq-statistic#87]
Using sidekiq enterprise 3.5.3. Tried sidekiq-statisic 1.1.0, 1.2.0 and HEAD (f27fcdf).

```
2015-11-23 13:44:51 - ArgumentError - argument out of range:
    /usr/lib/ruby/2.1.0/time.rb:264:in `local'
    /usr/lib/ruby/2.1.0/time.rb:264:in `make_time'
    /usr/lib/ruby/2.1.0/time.rb:331:in `parse'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension_helper.rb:9:in `formate_date'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension.rb:80:in `block (2 levels) in singleton class'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension.rb:77:in `each'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension.rb:77:in `block in singleton class'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension.rb:27:in `instance_eval'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension.rb:27:in `singleton class'
    /srv/core/shared/bundle/ruby/2.1.0/bundler/gems/sidekiq-statistic-f27fcdfe6fc0/lib/sidekiq/statistic/web_extension.rb:25:in `__tilt_174714020'
```

**Comment by davydovanton** [comment]
@jhollinger hello, thanks for report! :heart: 
Could you call this command and send me output of this?

```
redis-cli hgetall sidekiq:statistic
```

**Comment by jhollinger** [comment]
`(empty list or set)`

**Comment by jhollinger** [comment]
Oh that's b/c we're using a sidekiq namespace, so it's `sidekiq:sidekiq:statistic`. We have HIPAA concerns, so I can't send it to you. Could you tell me what to look for?

**Comment by davydovanton** [comment]
@jhollinger, I want to see what string you are use in `Time.parse` in `#formate_date` helper method. This error happened when you replace month and day in parsed string.

Thats why I want to ask you show me what contain `"2015-11-23:<WorkerName>:last_time"` key in redis statistic hash.

**Comment by jhollinger** [comment]
Got it. Here's a sampling of last_time values. They're obviously in the American date format. Are they expected to be in the more standard one?

    11/17/2015 0750 UTC
    11/15/2015 0500 UTC
    11/16/2015 0500 UTC
    11/22/2015 2342 UTC
    11/15/2015 2300 UTC
    11/21/2015 2256 UTC
    11/15/2015 0500 UTC
    11/23/2015 2000 UTC

**Comment by davydovanton** [comment]
Sorry, I use [this method](http://ruby-doc.org/core-2.2.3/Time.html#method-i-utc) for formate date in UTC. I think you need to use this method too.

**Comment by jhollinger** [comment]
Where is it that I would need to use that method?

**Comment by jhollinger** [comment]
ping

**Comment by davydovanton** [comment]
pong.
Please save data string in UTC format. You have a problem in parsing your data string in custom format.

**Comment by jhollinger** [comment]
Right, I mean what "data string?"

**Comment by davydovanton** [comment]
@mperham thanks! I think I need to rewrite code :grimacing:

**Comment by davydovanton** [comment]
Fixed it by @rbUUbr’s PR. Will close the issue
