### ISSUE TITLE
Does this gem play nicely with multiple sidekiq processes?

### ISSUE THREAD

**Issue by bobber205** [davydovanton/sidekiq-statistic#89]
We have two sidekiq processes running and it only seems to see our main queue/the project where the sidekiq-web gem is configured.

The sidekiq web interface shows us jobs processing through all of Sidekiq's scope of worker queues but this gem doesn't seem to see all queues?

**Comment by pchaganti** [comment]
👍

**Comment by rosshambrick** [comment]
Should this issue be closed?  I just set up my project with this gem and am seeing multiple queues across multiple processes being logged.

**Comment by davydovanton** [comment]
@rosshambrick I think yes. @bobber205 could you check this issue again?

**Comment by bobber205** [comment]
probably no longer an issue.
we stopped using this gem. It worked really well but was taking too much space in redis.
